DOM = [
    {"Domanda": "In presenza del segnale raffigurato un autocarro può sorpassare un motociclo", "Risposta": "True","img": "img/Dare_precedenza.png"},
    {"Domanda": "In presenza del segnale raffigurato un’autovettura può sorpassare un ciclomotore", "Risposta": "True","img": "img/Diritto_precedenza.png"},
    {"Domanda": "Il segnale raffigurato consente il transito agli autotreni, autoarticolati ed autosnodati", "Risposta": "True","img": "img/Limite_30.png"},
    {"Domanda": "Il segnale raffigurato si trova solo sulle strade extraurbane principali", "Risposta": "False","img": "img/svolta_destra.png"},
    {"Domanda": "Il segnale raffigurato è un segnale di precedenza", "Risposta": "True","img": "img/Stop_320m.png"},
    {"Domanda": "In presenza del segnale raffigurato bisogna comunque assicurarsi che i veicoli provenienti dalle strade laterali diano la precedenza", "Risposta": "True","img": "img/Diritto_precedenza.png"},
    {"Domanda": "Il segnale raffigurato è un segnale di prescrizione", "Risposta": "True","img": "img/Stop_320m.png"},
    {"Domanda": "Il segnale raffigurato preannuncia incrocio con precedenza rispetto ai soli veicoli provenienti da destra", "Risposta": "False","img": "img/Divieto_sorpasso.png"},
    {"Domanda": "Il segnale raffigurato preannuncia le corsie riservate agli autobus in servizio pubblico", "Risposta": "False","img": "img/svolta_destra.png"},
    {"Domanda": "In presenza del segnale raffigurato un autocarro può sorpassare un motociclo", "Risposta": "True","img": "img/Divieto_sorpasso.png"},
    {"Domanda": "In presenza del segnale raffigurato un’autovettura può sorpassare un ciclomotore", "Risposta": "True","img": "img/Diritto_precedenza.png"},
    {"Domanda": "Il segnale raffigurato consente il transito agli autotreni, autoarticolati ed autosnodati", "Risposta": "True","img": "img/Limite_30.png"},
    {"Domanda": "Il segnale raffigurato si trova solo sulle strade extraurbane principali", "Risposta": "False","img": "img/svolta_destra.png"},
    {"Domanda": "Il segnale raffigurato è un segnale di precedenza", "Risposta": "True","img": "img/Limite_50.png"},
    {"Domanda": "In presenza del segnale raffigurato bisogna comunque assicurarsi che i veicoli provenienti dalle strade laterali diano la precedenza", "Risposta": "True","img": "img/Diritto_precedenza.png"},
    {"Domanda": "Il segnale raffigurato è un segnale di prescrizione", "Risposta": "True","img": "img/Stop_320m.png"},
    {"Domanda": "Il segnale raffigurato preannuncia incrocio con precedenza rispetto ai soli veicoli provenienti da destra", "Risposta": "False","img": "img/Divieto_sorpasso.png"},
    {"Domanda": "Il segnale raffigurato preannuncia le corsie riservate agli autobus in servizio pubblico", "Risposta": "False","img": "img/svolta_destra.png"},
    {"Domanda": "In presenza del segnale raffigurato un autocarro può sorpassare un motociclo", "Risposta": "True","img": "img/Dare_precedenza.png"},
    {"Domanda": "In presenza del segnale raffigurato un’autovettura può sorpassare un ciclomotore", "Risposta": "True","img": "img/Limite_50.png"},
    {"Domanda": "Il segnale raffigurato consente il transito agli autotreni, autoarticolati ed autosnodati", "Risposta": "True","img": "img/Limite_30.png"},
    {"Domanda": "Il segnale raffigurato si trova solo sulle strade extraurbane principali", "Risposta": "False","img": "img/Divieto_sorpasso.png"},
    {"Domanda": "Il segnale raffigurato è un segnale di precedenza", "Risposta": "True","img": "img/Limite_50.png"},
    {"Domanda": "In presenza del segnale raffigurato bisogna comunque assicurarsi che i veicoli provenienti dalle strade laterali diano la precedenza", "Risposta": "True","img": "img/Diritto_precedenza.png"},
    {"Domanda": "Il segnale raffigurato è un segnale di prescrizione", "Risposta": "True","img": "img/Stop_320m.png"},
    {"Domanda": "Il segnale raffigurato preannuncia incrocio con precedenza rispetto ai soli veicoli provenienti da destra", "Risposta": "False","img": "img/Dare_precedenza.png"},
    {"Domanda": "Il segnale raffigurato preannuncia le corsie riservate agli autobus in servizio pubblico", "Risposta": "False","img": "img/Limite_50.png"},
    {"Domanda": "In presenza del segnale raffigurato bisogna comunque assicurarsi che i veicoli provenienti dalle strade laterali diano la precedenza", "Risposta": "True","img": "img/Diritto_precedenza.png"},
    {"Domanda": "Il segnale raffigurato è un segnale di prescrizione", "Risposta": "True","img": "img/Stop_320m.png"},
    {"Domanda": "Il segnale raffigurato preannuncia incrocio con precedenza rispetto ai soli veicoli provenienti da destra", "Risposta": "False","img": "img/Dare_precedenza.png"},
    {"Domanda": "Il segnale raffigurato preannuncia le corsie riservate agli autobus in servizio pubblico", "Risposta": "False","img": "img/Limite_50.png"}
    
]

